export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING = 'LOADING';

export const FETCH_PURCHASED = 'FETCH_PURCHASED';
export const FETCH_NOT_PURCHASED = 'FETCH_NOT_PURCHASED';
export const CREATE_ORDER = 'CREATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const PURCHASE_ORDER = 'PURCHASE_ORDER';
export const GET_USER_DATA = 'GET_USER_DATA';

export const FETCH_BEER = 'FETCH_BEER';
export const POST_BEER = 'POST_BEER';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
