export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING = 'LOADING';

export const FETCH_PURCHASED = 'FETCH_PURCHASED';
export const FETCH_NOT_PURCHASED = 'FETCH_NOT_PURCHASED';
export const CREATE_ORDER = 'CREATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';
export const PURCHASE_ORDER = 'PURCHASE_ORDER';
